# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_description', models.CharField(max_length=2000)),
                ('director', models.CharField(max_length=200)),
                ('poster_img', models.ImageField(default='C:/Users/Engineering/Desktop/Lae Lar/movie_project/poster_img/user1.jpg', upload_to='C:/Users/Engineering/Desktop/Lae Lar/movie_project/poster_img/user1.jpg')),
            ],
        ),
    ]
