# Generated by Django 2.0.1 on 2018-01-09 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_img',
            field=models.ImageField(default='C:/Users/Engineering/Desktop/Lae Lar/movie_project/poster_img/user1.jpg', upload_to='pic_folder/'),
        ),
    ]
